import { APP_NAME, complianceDisclaimer, complianceModeLabels } from "@/lib/constants";
import type { AuditData, Finding, Project, Scan } from "@/lib/types";
import { formatDateTime } from "@/lib/utils";

export function buildReportHtml(params: {
  data: AuditData;
  project: Project;
  scan: Scan;
  kind?: "executive" | "technical" | "vpat-draft";
}) {
  const findings = params.data.findings.filter((finding) => finding.projectId === params.project.id);
  const pages = params.data.scannedPages.filter((page) => page.scanId === params.scan.id);
  const manualChecks = params.data.manualChecks.filter((check) => check.projectId === params.project.id);
  const critical = findings.filter((finding) => finding.severity === "critical");
  const title =
    params.kind === "vpat-draft"
      ? `${params.project.name} VPAT/ACR Draft Preparation Notes`
      : `${params.project.name} Accessibility Audit ${params.kind === "technical" ? "Technical Report" : "Executive Summary"}`;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; font-family: Arial, sans-serif; color: #17212b; }
    body { margin: 0; padding: 40px; line-height: 1.45; }
    h1, h2, h3 { color: #08223d; line-height: 1.15; }
    h1 { font-size: 30px; margin-bottom: 6px; }
    h2 { font-size: 20px; margin-top: 30px; border-top: 2px solid #d7dee7; padding-top: 18px; }
    h3 { font-size: 15px; margin-bottom: 6px; }
    p { margin: 8px 0; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12px; }
    th, td { text-align: left; border-bottom: 1px solid #d7dee7; padding: 8px; vertical-align: top; }
    th { background: #edf5f4; color: #0b2c4f; }
    .meta { color: #4d5661; font-size: 13px; }
    .notice { border: 1px solid #b7d9d6; background: #eef8f7; padding: 12px; border-radius: 6px; }
    .score { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 18px 0; }
    .metric { border: 1px solid #d7dee7; border-radius: 6px; padding: 12px; }
    .metric strong { display: block; font-size: 24px; color: #08223d; }
    .critical { color: #b42318; font-weight: 700; }
    .serious { color: #c2410c; font-weight: 700; }
    .moderate { color: #91610f; font-weight: 700; }
    .minor { color: #276749; font-weight: 700; }
    code { background: #f6f7f8; padding: 2px 4px; border-radius: 3px; }
    pre { white-space: pre-wrap; background: #f6f7f8; padding: 10px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p class="meta">Generated by ${APP_NAME} ${escapeHtml(params.scan.toolVersion)} on ${escapeHtml(formatDateTime(new Date().toISOString()))}</p>
  <p class="meta">Project: ${escapeHtml(params.project.name)} | Standard: ${escapeHtml(complianceModeLabels[params.project.complianceMode])} | Scan: ${escapeHtml(params.scan.id)}</p>

  <section class="notice" aria-label="Important limitation">
    <strong>Important limitation:</strong> ${escapeHtml(complianceDisclaimer)}
  </section>

  <h2>Executive Summary</h2>
  <p>${escapeHtml(params.scan.summary.label)}. The score below is an explainable risk estimate, not a legal compliance certification.</p>
  <div class="score">
    <div class="metric"><span>Risk score</span><strong>${params.scan.summary.riskScore}</strong></div>
    <div class="metric"><span>Critical blockers</span><strong>${params.scan.summary.criticalBlockers}</strong></div>
    <div class="metric"><span>Pages scanned</span><strong>${params.scan.summary.pagesScanned}</strong></div>
    <div class="metric"><span>Confidence</span><strong>${escapeHtml(params.scan.summary.confidence)}</strong></div>
  </div>

  <h2>Methodology</h2>
  <p>AccessAudit crawled rendered pages in Chromium, ran axe-core checks, collected DOM snapshots and screenshots, tested desktop and mobile viewports, explored keyboard focus order, and created manual-review tasks for checks automation cannot reliably prove.</p>
  <p>URLs scanned: ${pages.length ? pages.map((page) => escapeHtml(page.url)).join(", ") : "No pages recorded for this scan."}</p>

  <h2>Recommended Remediation Order</h2>
  <ol>
    <li>Fix critical keyboard, focus, form, and name/role/value blockers first.</li>
    <li>Resolve serious WCAG A and AA failures that affect shared templates.</li>
    <li>Complete manual checks for media, documents, authentication, cognition, and assistive technology sanity testing.</li>
    <li>Re-scan fixed templates and compare against prior scan history.</li>
  </ol>

  <h2>Critical Findings</h2>
  ${critical.length ? findingsTable(critical) : "<p>No open critical findings were recorded in this report.</p>"}

  <h2>Score Breakdown</h2>
  <table>
    <tbody>
      <tr><th>WCAG A pass estimate</th><td>${params.scan.summary.wcagAPassEstimate}%</td></tr>
      <tr><th>WCAG AA pass estimate</th><td>${params.scan.summary.wcagAAPassEstimate}%</td></tr>
      <tr><th>Serious issues</th><td>${params.scan.summary.seriousIssues}</td></tr>
      <tr><th>Moderate issues</th><td>${params.scan.summary.moderateIssues}</td></tr>
      <tr><th>Manual review completion</th><td>${params.scan.summary.manualReviewCompletion}%</td></tr>
      <tr><th>Templates affected</th><td>${params.scan.summary.templatesAffected}</td></tr>
    </tbody>
  </table>
  <ul>
    ${params.scan.summary.explanation.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}
  </ul>

  <h2>Manual Review Status</h2>
  <table>
    <thead><tr><th>Check</th><th>Principle</th><th>Status</th><th>Priority</th><th>Notes</th></tr></thead>
    <tbody>
      ${manualChecks
        .map(
          (check) => `<tr><td>${escapeHtml(check.title)}</td><td>${escapeHtml(check.principle)}</td><td>${escapeHtml(check.status)}</td><td>${escapeHtml(check.priority)}</td><td>${escapeHtml(check.notes ?? "")}</td></tr>`
        )
        .join("")}
    </tbody>
  </table>

  <h2>Full Findings Appendix</h2>
  ${findingsTable(findings)}

  ${
    params.kind === "vpat-draft"
      ? `<h2>VPAT/ACR Draft Support Only</h2><p>This section is preparation support, not a completed VPAT or Accessibility Conformance Report. An authorized accessibility professional should review evidence, conformance levels, exceptions, and product scope.</p>${vpatDraft(findings)}`
      : ""
  }
</body>
</html>`;
}

function findingsTable(findings: Finding[]) {
  if (!findings.length) return "<p>No findings.</p>";
  return `<table>
    <thead>
      <tr>
        <th>Severity</th>
        <th>Finding</th>
        <th>WCAG / 508 Mapping</th>
        <th>Status</th>
        <th>Recommended Fix</th>
      </tr>
    </thead>
    <tbody>
      ${findings
        .map(
          (finding) => `<tr>
            <td class="${escapeHtml(finding.severity)}">${escapeHtml(finding.severity)}</td>
            <td><strong>${escapeHtml(finding.title)}</strong><br />${escapeHtml(finding.whyItMatters)}<br /><code>${escapeHtml(finding.selector ?? "Page-level")}</code></td>
            <td>${finding.wcag.map((ref) => `${escapeHtml(ref.standard)} ${escapeHtml(ref.criterion)} ${escapeHtml(ref.name)}`).join("<br />")}</td>
            <td>${escapeHtml(finding.status)}</td>
            <td>${escapeHtml(finding.remediation.fix)}</td>
          </tr>`
        )
        .join("")}
    </tbody>
  </table>`;
}

function vpatDraft(findings: Finding[]) {
  const grouped = new Map<string, Finding[]>();
  for (const finding of findings) {
    for (const ref of finding.wcag) {
      const key = `${ref.standard} ${ref.criterion} ${ref.name}`;
      grouped.set(key, [...(grouped.get(key) ?? []), finding]);
    }
  }

  return `<table>
    <thead><tr><th>Criterion</th><th>Draft support note</th></tr></thead>
    <tbody>
      ${Array.from(grouped.entries())
        .map(([criterion, items]) => `<tr><td>${escapeHtml(criterion)}</td><td>${items.length} related finding(s). Conformance impact requires expert review.</td></tr>`)
        .join("")}
    </tbody>
  </table>`;
}

function escapeHtml(value: string | number) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
